spring:
  h2:
    console:
      enabled: true
      path: /h2
    datasource:
      url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create #운영환경에 배포시 반드시 none으로 바꿀 것!!!!
    show-sql: true
    use-new-id-generator-mappings: true

