spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306
    username: "localtest"
    password: "pre20test"
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    use-new-id-generator-mappings: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#jwt:
#  secret-key: ${JWT_SKY}
#  access-token-expiration-seconds: 7200
#  refresh-token-expiration-seconds: 18000